# Generated by Django 3.1.1 on 2020-09-10 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kiosks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('icon', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSupplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('street_address', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField()),
                ('id_number', models.IntegerField()),
                ('date_added', models.DateField()),
                ('profile_picture', models.ImageField(upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('supplier_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('number_in_stock', models.IntegerField()),
                ('product_image', models.ImageField(upload_to='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.productcategory')),
                ('kiosk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiosks.kiosk')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.productsupplier')),
            ],
        ),
    ]
