# Generated by Django 3.1.1 on 2020-09-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_productreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(height_field=150, upload_to='images/', width_field=150),
        ),
    ]
